[mod-nlb] don't declare mixin within if
java.io.IOException: Could not compile SASS style sheet: Error: Functions may not be defined within control directives or other mixins

Fix for error introduced in d1b7a5eb8fe20b9cacaa102ef20487b8f4f29ccc